hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiment.dir_name=/work/fis1/RT-DeepRL/outputs
    - wandb.entity=alessandro-montenegro-polimi
    - wandb.project=temp
    - wandb.tags=[]
    - experiment.env_name=Hopper-v5
    - experiment.norm_reward=False
    - experiment.total_timesteps=1000000
    - experiment.window_size=4
    - experiment.weight_type=naive
    - experiment.seed=0
  job:
    name: learn_ppo_test
    chdir: false
    override_dirname: experiment.dir_name=/work/fis1/RT-DeepRL/outputs,experiment.env_name=Hopper-v5,experiment.norm_reward=False,experiment.seed=0,experiment.total_timesteps=1000000,experiment.weight_type=naive,experiment.window_size=4,wandb.entity=alessandro-montenegro-polimi,wandb.project=temp,wandb.tags=[]
    id: ???
    num: ???
    config_name: ppo_from_geppo
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /work/fis1/RT-DeepRL
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /work/fis1/RT-DeepRL/config/ppo
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
wandb:
  entity: alessandro-montenegro-polimi
  project: temp
  sync_tensorboard: true
  tags: []
experiment:
  env_name: Hopper-v5
  n_envs: 1
  dir_name: /work/fis1/RT-DeepRL/outputs
  norm_reward: false
  norm_obs: true
  total_timesteps: 1000000
  policy_type: MlpPolicy
  learning_rate: 0.0003
  n_steps: 2048
  n_minibatch: 32
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.97
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  tensorboard_log: null
  policy_kwargs: null
  verbose: 0
  seed: 0
  device: cpu
  window_size: 4
  on_policy_critic: true
  weight_type: naive
  sequential_window_training: false
  fresh_adv: false
  eval_freq: 10000
  n_eval_episodes: 50
  n_eval_envs: 1
