wandb:
  project: sb3-a2c-inverted-pendulum-v2
  sync_tensorboard: true
  tags: null


experiment:
  # ENV
  env_name: InvertedPendulum-v5
  n_envs: 1 # 64   <=====

  # Training
  total_timesteps: 3e5
  dir_name: null
  render: false
  model_save_freq: 10000

  # A2C Parameters
  policy_type: MlpPolicy
  learning_rate: 7e-4 # 7e-4 
  n_steps: 200 # 5   <=====
  gamma: 1 # 0.99
  gae_lambda: 1.0 # 1.0
  ent_coef: 0.01 # 0.0   <=====
  vf_coef: 0.5 # 0.5
  max_grad_norm: 0.5 # 0.5
  rms_prop_eps: 1e-5 # 1e-5
  use_rms_prop: false # true
  use_sde: false # false
  sde_sample_freq: -1 # -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null 
  normalize_advantage: true # false
  stats_window_size: 100 # 100
  tensorboard_log: null
  policy_kwargs:
    net_arch: [32, 32]  #  <=====
  verbose: 0
  seed: 2026
  device: cpu

  # Reusing Trajectories
  window_size: 1 
  on_policy_critic: false
  weight_type: naive # "naive" or "bh"

hydra:
  run:
    dir: ${experiment.dir_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: run_${hydra.job.num}