wandb:
  entity: null
  project: null
  sync_tensorboard: true
  tags: null

experiment:
  # ENV
  env_name: null
  n_envs: 4 # 4           
  dir_name: null
  norm_reward: false
  norm_obs: true

  # Training
  total_timesteps: 1e6 

  # PPO Parameters
  policy_type: MlpPolicy
  learning_rate: !!float 6e-4 
  n_steps: 1024 # 256         
  n_minibatch: 16
  n_epochs: 10         
  gamma: 0.9999          
  gae_lambda: 0.98     
  clip_range: 0.2      
  clip_range_vf: null
  normalize_advantage: true 
  ent_coef: 0.0            
  vf_coef: 0.5             
  max_grad_norm: 0.5       
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  tensorboard_log: null
  policy_kwargs: 
  verbose: 0
  seed: 2026
  device: cpu

  # Reusing Trajectories
  window_size: 1 
  on_policy_critic: true
  weight_type: naive # "naive" or "bh"
  sequential_window_training: false # true
  fresh_adv: false # true

  # Eval parameters
  eval_freq: 10_000
  n_eval_episodes: 50
  n_eval_envs: 1