# parameters from alessandro's tuning for reacher (rl zoo)

wandb:
  entity: null
  project: null
  sync_tensorboard: true
  tags: null

experiment:
  # ENV
  env_name: null
  n_envs: 1 # 4           
  dir_name: null
  norm_reward: false
  norm_obs: true
    
  # Training
  total_timesteps: 1e6 

  # PPO Default Parameters
  policy_type: MlpPolicy
  learning_rate: 0.000104019 
  n_steps: 512 # 256         
  n_minibatch: 16
  n_epochs: 5         
  gamma: 0.9  
  gae_lambda: 1.0    
  clip_range: 0.3     
  clip_range_vf: null
  normalize_advantage: true 
  ent_coef: 7.52585e-08            
  vf_coef: 0.950368             
  max_grad_norm: 0.9      
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  tensorboard_log: null
  policy_kwargs: 
  verbose: 0
  seed: 2026
  device: cpu

  # Reusing Trajectories
  window_size: 1 
  on_policy_critic: true
  weight_type: naive # "naive" or "bh"
  sequential_window_training: false # true
  fresh_adv: false # true
  balanced_batches: true

  # Eval parameters
  eval_freq: 10000
  n_eval_episodes: 50
  n_eval_envs: 1