wandb:
  project: rt-ppo-ho
  sync_tensorboard: true
  tags: null

experiment:
  # ENV
  env_name: Hopper-v5   # paper usa v3
  n_envs: 1             
  total_timesteps: 1e6 
  dir_name: results
  render: false
  
  # PPO Parameters (from paper)
  policy_type: MlpPolicy
  learning_rate: 3e-4          # η
  n_steps: 2048                # N = 2048 con n_envs=1
  n_minibatch: 32              # minibatches per epoch
  n_epochs: 10                 
  gamma: 0.995                
  gae_lambda: 0.97             
  clip_range: 0.2              
  clip_range_vf: null
  normalize_advantage: true 
    
  # non specificati → default paper-like
  ent_coef: 0.0                
  vf_coef: 0.5                 
  max_grad_norm: 0.5           

  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  tensorboard_log: null      

  policy_kwargs:
    log_std_init: 0.0          # std = 1.0
    ortho_init: true
    activation_fn: nn.Tanh     # paper usa tanh
    net_arch:
      pi: [64, 64]
      vf: [64, 64]

  verbose: 0
  seed: 2026
  device: cpu

  # Reusing Trajectories (tuo setup → invariato)
  window_size: 1 
  on_policy_critic: true
  weight_type: naive
  sequential_window_training: false
  fresh_adv: false