hydra:
  run:
    dir: ${experiment.dir_name}/hydra/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  project: reinforce
  sync_tensorboard: true
  tags: []

experiment:
  # Environment
  env_name: CartPole-v1
  n_envs: 20
  total_timesteps: 1_000_000
  dir_name: /storage/fis1/RT-DeepRL/results
  render: false
  normalize_obs: true
  normalize_reward: false

  # REINFORCE hyperparameters
  policy_type: MlpPolicy
  learning_rate: 1e-3
  n_steps: 1000           # maximum trajectory horizon (hard cap)
  gamma: 1
  max_grad_norm: null
  ent_coef: 0.0           
  normalize_returns: false 
  # Exploration
  use_sde: false
  sde_sample_freq: -1

  # Logging / evaluation
  stats_window_size: 100
  eval_freq: null # 10_000
  n_eval_episodes: 50
  verbose: 0
  seed: 2026
  device: cpu

  # Policy architecture
  policy_kwargs:
    net_arch: [64, 64]
    activation_fn: tanh
    log_std_init: 0.0
    ortho_init: true
    learn_std: false
